image: papitz/psys-runner:latest

build:
  stage: build
  tags: [Linux]
  script:
    - mkdir build
    - cmake -S . -B build
    - cmake --build build

  artifacts:
    paths:
      - build/HeatMatrix

ctest:
  stage: test
  script:
    - cd test
    - cmake .
    - cmake --build .
    - ./t_HeatMatrix --gtest_output="xml:unittestResults.xml"
  tags: [Linux]
  artifacts:
    paths:
      - test/unittestResults.xml
    reports:
      junit: test/unittestResults.xml
