image: debian:bullseye
build:
    stage: build
    tags: [Linux]
    before_script:
        - apt-get update
        - apt-get install -y build-essential cmake
        - apt-get install -y libopencv-dev
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
