image: papitz/psys-runner:latest

# build:
#   stage: build
#   tags: [Linux]
#   # before_script:
#   #   - apt-get update
#   #   - apt-get install -y build-essential cmake
#   #   - apt-get install -y libopencv-dev
#   #   - apt-get install -y git
#   script:
#     - mkdir build
#     - cmake -S . -B build
#     - cmake --build build
#
#   artifacts:
#     paths:
#       - build/HeatMatrix
#       - build/t_HeatMatrix

ctest:
  stage: test
  script:
    - cd test
    - cmake .
    - cmake --build .
    - ctest --output-on-failure
  tags: [Linux]
  artifacts:
    when: always
    paths:
      - test/Testing/Temporary/LastTest.log
    reports:
      junit: test/Testing/Temporary/LastTest.log
