.alpine_cmake_test: &alpine_cmake_test
  image: alpine
  before_script:
    - apk update
    - apk add cmake make g++ git opencv-dev libgomp openmpi openmpi-dev
    - apk add valgrind
    - sudo ln -s /usr/include/opencv4/opencv2 /usr/include/opencv2

build:
  stage: build
  <<: *alpine_cmake_test
  tags: [Linux]
  script:
    - mkdir build
    - cmake -S . -B build
    - cmake --build build
    - cd mpi
    - mpicxx -o mpi_run mpi_main.cpp ../src/HeatMatrix.cpp ../src/heat_functions.cpp

  artifacts:
    paths:
      - build/HeatMatrix
      - mpi/mpi_run

gtest:
  stage: test
  <<: *alpine_cmake_test
  script:
    - mpiexec -n 4 ./mpi/mpi_run
    - cd test
    - cmake .
    - cmake --build .
    - ./t_HeatMatrix --gtest_output="xml:unittestResults.xml"
  tags: [Linux]
  artifacts:
    paths:
      - test/unittestResults.xml
    reports:
      junit: test/unittestResults.xml

memcheck:
  stage: test
  <<: *alpine_cmake_test
  script:
    - cd build
    - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --show-error-list=yes ./HeatMatrix
    - valgrind --tool=helgrind -s ./HeatMatrix 100 100 1500.0 100 0.025 0.1 1 4 0
  tags: [Linux]
