# image: papitz/psys-runner:latest
#
# build:
#   stage: build
#   tags: [Linux]
#   script:
#     - mkdir build
#     - cmake -S . -B build
#     - cmake --build build
#
#   artifacts:
#     paths:
#       - build/HeatMatrix
#
# ctest:
#   stage: test
#   script:
#     - cd test
#     - cmake .
#     - cmake --build .
#     - ./t_HeatMatrix --gtest_output="xml:unittestResults.xml"
#   tags: [Linux]
#   artifacts:
#     paths:
#       - test/unittestResults.xml
#     reports:
#       junit: test/unittestResults.xml
.alpine_cmake_test: &alpine_cmake_test
  # image: alpine
  # before_script:
  #   - apk update
  #   - apk add cmake make g++ git opencv-dev libgomp
  #   - apk add valgrind
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y cmake make g++ git libopencv-dev libgomp1
    - apt-get install -y valgrind

build:
  stage: build
  <<: *alpine_cmake_test
  tags: [Linux]
  script:
    - mkdir build
    - cmake -S . -B build
    - cmake --build build

  artifacts:
    paths:
      - build/HeatMatrix

gtest:
  stage: test
  <<: *alpine_cmake_test
  script:
    - cd test
    - cmake .
    - cmake --build .
    - ./t_HeatMatrix --gtest_output="xml:unittestResults.xml"
  tags: [Linux]
  artifacts:
    paths:
      - test/unittestResults.xml
    reports:
      junit: test/unittestResults.xml

memcheck:
  stage: test
  <<: *alpine_cmake_test
  script:
    - cd build
    - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --show-error-list=yes ./HeatMatrix
    - valgrind --tool=helgrind -s ./HeatMatrix 100 100 1500.0 100 0.025 0.1 1 4 0
  tags: [Linux]
